version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      # - --entrypoints.web.address=:80
      - --providers.docker.exposedbydefault=true
      - --providers.docker.network=deploy
      - --log.level=DEBUG
      - --log.filePath=log/traefik.log
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.fugoku.pro`)"
    networks:
      - deploy

networks:
  deploy:
    external: false
