---
- name: Install and Configure Traefik Container
  hosts: web
  become: true

  tasks:
    - name: Create directory for Traefik configuration
      file:
        path: /etc/traefik
        state: directory

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /etc/traefik/docker-compose.yml
    
    # - name: Create Docker network if it doesn't exist
    #   command: docker network create web
    #   ignore_errors: true

    - name: Deploy Traefik 
      docker_compose:
        project_name: traefik
        project_src: /etc/traefik