---
- name: Install and Configure Traefik Container
  hosts: web
  become: true

  tasks:
    - name: Create directory for Traefik configuration
      file:
        path: /etc/traefik
        state: directory

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /etc/traefik/docker-compose.yml

    
    - name: Create Docker network if it doesn't exist
      command: docker network create web
      ignore_errors: true


    - name: Ensure Traefik container is running
      docker_container:
        name: traefik
        image: traefik:v2.5
        state: started
        restart_policy: always
        command: /entrypoint.sh
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - name: web
            aliases:
              - traefik
        published_ports:
          - "80:80"
