version: "3.9"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.portainer.rule=Host(`portainer.fugoku.pro`)"
    - "traefik.http.routers.portainer.tls=true"
    - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
    - "traefik.http.services.portainer.loadbalancer.server.port=9433"
    - "traefik.http.services.portainer.loadbalancer.passhostheader=true"
    - "traefik.docker.network=deploy"
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
    networks:
      - deploy
networks:
  deploy:
    external: false